import React from 'react';
import { Lock, Package, RefreshCw, Rocket, Sparkles, Target, TrendingUp, Users, WalletCards } from 'lucide-react';
import { Link } from 'react-router-dom';
import toast from 'react-hot-toast';
import { useAppStore } from '../store';
import { buildAutonomousGrowthEngine, type AutonomousGrowthEngineResult, type GrowthOpportunity } from '../lib/autonomousGrowthEngine';
import { cn } from '../utils/cn';
import { formatCurrency } from '../utils/helpers';

export const AutonomousGrowthEngine: React.FC = () => {
  const { currentBusiness } = useAppStore();
  const [result, setResult] = React.useState<AutonomousGrowthEngineResult | null>(null);
  const [isLoading, setIsLoading] = React.useState(true);
  const businessId = currentBusiness?.id;
  const load = React.useCallback(async () => { if (!businessId) { setIsLoading(false); return; } setIsLoading(true); try { setResult(await buildAutonomousGrowthEngine(businessId)); } catch (error) { toast.error(error instanceof Error ? error.message : 'Autonomous Growth Engine unavailable.'); } finally { setIsLoading(false); } }, [businessId]);
  React.useEffect(() => { load(); }, [load]);
  if (isLoading && !result) return <div className="rounded-3xl border border-purple-100 bg-white p-10 text-center"><RefreshCw className="mx-auto h-8 w-8 animate-spin text-purple-600" /><p className="mt-4 font-semibold text-slate-600">Finding growth opportunities from live BizGuard data...</p></div>;
  if (result?.gate.access === 'locked') return <UpgradeGate plan={result.gate.planCode} onRefresh={load} />;
  const score = result?.growthScore;
  return <div className="space-y-6">
    <div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div><div className="inline-flex items-center gap-2 rounded-full bg-black px-3 py-1 text-xs font-black uppercase tracking-[0.2em] text-purple-100"><Rocket className="h-4 w-4" /> Autonomous Growth Engine™</div><h1 className="mt-3 text-3xl font-black text-slate-900">Grow The Business — Not Just Track It</h1><p className="mt-2 max-w-4xl text-slate-600">AI identifies product, customer, revenue, profit, inventory and expansion opportunities from real BizGuard data.</p>{result?.gate.access === 'limited' && <p className="mt-2 rounded-xl bg-amber-50 px-3 py-2 text-sm font-bold text-amber-700">Limited Pro preview. Upgrade to Business or Enterprise for full playbooks and expansion advisor.</p>}</div><button onClick={load} className="inline-flex items-center gap-2 rounded-xl border border-purple-200 bg-white px-4 py-2 text-sm font-black text-purple-700"><RefreshCw className={cn('h-4 w-4', isLoading && 'animate-spin')} />Refresh Growth Engine</button></div>
    <div className="rounded-3xl border border-purple-200 bg-gradient-to-br from-slate-950 via-purple-950 to-black p-6 text-white"><div className="grid gap-6 xl:grid-cols-[1fr_260px]"><div><div className="flex items-center gap-3"><Sparkles className="h-7 w-7 text-purple-300" /><h2 className="text-xl font-black">{result?.providerResult.title || 'Autonomous Growth Engine'}</h2></div><p className="mt-3 text-purple-50/80">{result?.providerResult.summary}</p><p className="mt-2 text-xs text-purple-100/70">Provider: {result?.providerUsed} · Fallback: {result?.providerFallbackUsed ? 'Yes' : 'No'}</p></div><div className="rounded-2xl border border-white/10 bg-white/10 p-5"><p className="text-sm text-purple-100">AI Growth Score</p><p className="text-5xl font-black">{score?.overall || 0}/100</p></div></div></div>
    <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-5"><Metric label="Revenue Growth" value={`${score?.revenueGrowth || 0}/100`} icon={TrendingUp} /><Metric label="Customer Growth" value={`${score?.customerGrowth || 0}/100`} icon={Users} /><Metric label="Inventory Growth" value={`${score?.inventoryGrowth || 0}/100`} icon={Package} /><Metric label="Profit Growth" value={`${score?.profitGrowth || 0}/100`} icon={WalletCards} /><Metric label="Expansion Ready" value={`${score?.expansionReadiness || 0}/100`} icon={Rocket} /></div>
    <div className="grid grid-cols-1 gap-4 md:grid-cols-4"><Metric label="Projected Revenue" value={formatCurrency(result?.summary.projectedRevenueImpact || 0)} icon={TrendingUp} /><Metric label="Projected Profit" value={formatCurrency(result?.summary.projectedProfitImpact || 0)} icon={WalletCards} /><Metric label="Customer Plays" value={String(result?.summary.customerOpportunities || 0)} icon={Users} /><Metric label="Inventory Actions" value={String(result?.summary.inventoryActions || 0)} icon={Package} /></div>
    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 flex items-center gap-2 text-xl font-black text-slate-900"><Target className="h-6 w-6 text-purple-600" /> Growth Opportunity Feed</h2><div className="grid gap-4 xl:grid-cols-2">{result?.opportunities.map((item, index) => <OpportunityCard key={item.id} item={item} index={index + 1} />)}</div>{!result?.opportunities.length && <p className="text-sm text-slate-500">No growth opportunities yet. Record sales, products, customers and payments to activate the engine.</p>}</section>
    <section className="grid gap-6 xl:grid-cols-3"><Panel title="Fastest-Growing Products" items={(result?.fastestGrowingProducts || []).map((p) => `${p.name}: ${p.demandTrend}% trend, ${formatCurrency(p.revenue)} revenue. ${p.action}`)} /><Panel title="Slowest-Moving Products" items={(result?.slowestMovingProducts || []).map((p) => `${p.name}: ${p.turnover}x turnover. ${p.action}`)} /><Panel title="Expansion Advisor" items={[`${result?.expansionAdvisor.recommendation || ''}`, `Confidence ${result?.expansionAdvisor.confidence || 0}% · Risk ${result?.expansionAdvisor.risk || 'Moderate'} · Projected revenue +${result?.expansionAdvisor.projectedRevenueIncreasePercent || 0}%`, result?.expansionAdvisor.rationale || '']} /></section>
    <section className="grid gap-6 xl:grid-cols-5"><Panel title="Revenue Growth Plan" items={result?.playbooks.revenueGrowthPlan || []} /><Panel title="Retention Plan" items={result?.playbooks.customerRetentionPlan || []} /><Panel title="Inventory Growth Plan" items={result?.playbooks.inventoryGrowthPlan || []} /><Panel title="Expansion Plan" items={result?.playbooks.expansionPlan || []} /><Panel title="Profit Improvement" items={result?.playbooks.profitImprovementPlan || []} /></section>
  </div>;
};
const UpgradeGate = ({ plan, onRefresh }: { plan: string; onRefresh: () => void }) => <div className="rounded-3xl border border-purple-200 bg-purple-50 p-10 text-center"><Lock className="mx-auto h-10 w-10 text-purple-700" /><h1 className="mt-4 text-3xl font-black text-slate-900">Upgrade to Business or Enterprise to unlock Autonomous Growth Engine™</h1><p className="mt-3 text-slate-600">Current plan: {plan}. Pro has optional limited preview; Business and Enterprise unlock full growth playbooks.</p><div className="mt-6 flex justify-center gap-3"><Link to="/subscription" className="rounded-xl bg-purple-600 px-5 py-3 text-sm font-black text-white">Upgrade Plan</Link><button onClick={onRefresh} className="rounded-xl border border-slate-200 bg-white px-5 py-3 text-sm font-black">Re-check</button></div></div>;
const Metric = ({ label, value, icon: Icon }: { label: string; value: string; icon: typeof TrendingUp }) => <div className="rounded-2xl border border-slate-200 bg-white p-5"><Icon className="h-5 w-5 text-purple-600" /><p className="mt-3 text-xs font-black uppercase text-slate-500">{label}</p><p className="mt-1 text-2xl font-black text-slate-900">{value}</p></div>;
const OpportunityCard = ({ item, index }: { item: GrowthOpportunity; index: number }) => <div className="rounded-2xl border border-slate-200 bg-gradient-to-br from-white to-purple-50/50 p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wide text-purple-700">Opportunity #{index} · {item.category}</p><h3 className="mt-1 font-black text-slate-900">{item.title}</h3></div><span className="rounded-full bg-black px-2 py-1 text-xs font-black text-purple-100">{item.confidence}%</span></div><div className="mt-4 grid grid-cols-2 gap-3"><div><p className="text-xs text-slate-500">Expected Revenue</p><p className="font-black text-slate-900">{formatCurrency(item.expectedRevenue)}</p></div><div><p className="text-xs text-slate-500">Expected Profit</p><p className="font-black text-slate-900">{formatCurrency(item.expectedProfit)}</p></div></div><p className="mt-4 font-semibold text-slate-700">Action: {item.action}</p><p className="mt-2 text-sm text-slate-500">{item.rationale}</p></div>;
const Panel = ({ title, items }: { title: string; items: string[] }) => <div className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="mb-3 font-black text-slate-900">{title}</h3><div className="space-y-2">{items.length ? items.map((item) => <div key={item} className="rounded-xl bg-slate-50 p-3 text-sm text-slate-700">{item}</div>) : <p className="text-sm text-slate-500">No playbook items yet.</p>}</div></div>;
export default AutonomousGrowthEngine;
