import React from 'react';
import { Plus, Search, Filter, DollarSign, AlertCircle, Download, Phone, Mail, TrendingUp, RefreshCw, X, CreditCard, RotateCcw, StickyNote, Printer } from 'lucide-react';
import toast from 'react-hot-toast';
import { cn } from '../utils/cn';
import { formatCurrency, formatDate, getInitials } from '../utils/helpers';
import { supabase } from '../lib/supabase';
import { useAppStore } from '../store';
import type { Database } from '../lib/database.types';

type CustomerRow = Database['public']['Tables']['customers']['Row'];
type InvoiceRow = Database['public']['Tables']['invoices']['Row'];
type PaymentRow = Database['public']['Tables']['payments']['Row'];
type PaymentInsert = Database['public']['Tables']['payments']['Insert'];
type CollectionNoteRow = Database['public']['Tables']['collection_notes']['Row'];

type CustomerStatus = 'active' | 'inactive' | 'overdue';
type InvoiceStatus = 'paid' | 'partial' | 'pending' | 'overdue' | 'cancelled';
type AgingBucket = '0-30' | '31-60' | '61-90' | '91-180' | '180+';

interface CustomerView extends CustomerRow { status: CustomerStatus; }
interface InvoiceView extends InvoiceRow { customerName: string; statusView: InvoiceStatus; agingBucket: AgingBucket; daysOverdue: number; }

interface CustomerFormState { name: string; email: string; phone: string; address: string; credit_limit: string; }
interface PaymentFormState { invoiceId: string; customerId: string; amount: string; method: 'cash' | 'card' | 'mobile' | 'bank_transfer'; reference: string; notes: string; }
interface NoteFormState { customerId: string; invoiceId: string; note: string; priority: 'low' | 'normal' | 'high' | 'urgent'; nextFollowUpAt: string; }

const emptyCustomerForm: CustomerFormState = { name: '', email: '', phone: '', address: '', credit_limit: '0' };
const emptyPaymentForm: PaymentFormState = { invoiceId: '', customerId: '', amount: '0', method: 'cash', reference: '', notes: '' };
const emptyNoteForm: NoteFormState = { customerId: '', invoiceId: '', note: '', priority: 'normal', nextFollowUpAt: '' };

const statusColors: Record<string, string> = {
  active: 'bg-green-100 text-green-700', inactive: 'bg-gray-100 text-gray-700', overdue: 'bg-red-100 text-red-700', paid: 'bg-green-100 text-green-700', partial: 'bg-yellow-100 text-yellow-700', pending: 'bg-blue-100 text-blue-700', cancelled: 'bg-gray-100 text-gray-700'
};
const agingColors: Record<AgingBucket, string> = { '0-30': 'bg-green-50 text-green-700', '31-60': 'bg-yellow-50 text-yellow-700', '61-90': 'bg-orange-50 text-orange-700', '91-180': 'bg-red-50 text-red-700', '180+': 'bg-red-950 text-white' };

const toNumber = (value: string, fallback = 0) => { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : fallback; };
const daysPastDue = (date: string) => Math.max(0, Math.floor((Date.now() - new Date(date).getTime()) / (1000 * 60 * 60 * 24)));
const agingBucket = (days: number): AgingBucket => days <= 30 ? '0-30' : days <= 60 ? '31-60' : days <= 90 ? '61-90' : days <= 180 ? '91-180' : '180+';
const getInvoiceStatus = (invoice: InvoiceRow): InvoiceStatus => Number(invoice.balance) <= 0 ? 'paid' : new Date(invoice.due_date) < new Date() ? 'overdue' : Number(invoice.amount_paid) > 0 ? 'partial' : invoice.status === 'pending' ? 'pending' : 'partial';
const getCustomerStatus = (customer: CustomerRow, invoices: InvoiceRow[]): CustomerStatus => !customer.is_active ? 'inactive' : invoices.some((invoice) => invoice.customer_id === customer.id && Number(invoice.balance) > 0 && new Date(invoice.due_date) < new Date()) ? 'overdue' : 'active';

const csv = (headers: string[], rows: Array<Array<string | number | null | undefined>>) => [headers, ...rows].map((row) => row.map((cell) => `"${String(cell ?? '').replace(/"/g, '""')}"`).join(',')).join('\n');
const download = (filename: string, content: string, type = 'text/csv;charset=utf-8;') => { const blob = new Blob([content], { type }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); };

export const Debtors: React.FC = () => {
  const { currentBusiness, user } = useAppStore();
  const businessId = currentBusiness?.id;
  const [customers, setCustomers] = React.useState<CustomerView[]>([]);
  const [invoices, setInvoices] = React.useState<InvoiceView[]>([]);
  const [payments, setPayments] = React.useState<PaymentRow[]>([]);
  const [notes, setNotes] = React.useState<CollectionNoteRow[]>([]);
  const [searchTerm, setSearchTerm] = React.useState('');
  const [statusFilter, setStatusFilter] = React.useState<string>('all');
  const [activeTab, setActiveTab] = React.useState<'customers' | 'invoices' | 'payments' | 'aging' | 'notes'>('customers');
  const [showAddCustomerModal, setShowAddCustomerModal] = React.useState(false);
  const [showPaymentModal, setShowPaymentModal] = React.useState(false);
  const [showNoteModal, setShowNoteModal] = React.useState(false);
  const [customerForm, setCustomerForm] = React.useState<CustomerFormState>(emptyCustomerForm);
  const [paymentForm, setPaymentForm] = React.useState<PaymentFormState>(emptyPaymentForm);
  const [noteForm, setNoteForm] = React.useState<NoteFormState>(emptyNoteForm);
  const [isLoading, setIsLoading] = React.useState(true);
  const [isSaving, setIsSaving] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);

  const loadDebtors = React.useCallback(async () => {
    if (!businessId) { setError('No business is selected.'); setIsLoading(false); return; }
    setIsLoading(true); setError(null);
    const [customersResult, invoicesResult, paymentsResult, notesResult] = await Promise.all([
      supabase.from('customers').select('*').eq('business_id', businessId).order('created_at', { ascending: false }),
      supabase.from('invoices').select('*').eq('business_id', businessId).order('created_at', { ascending: false }),
      supabase.from('payments').select('*').eq('business_id', businessId).order('created_at', { ascending: false }),
      supabase.from('collection_notes').select('*').eq('business_id', businessId).order('created_at', { ascending: false }),
    ]);
    const firstError = customersResult.error || invoicesResult.error || paymentsResult.error;
    if (firstError) { setError(firstError.message); toast.error(`Could not load debtors: ${firstError.message}`); setIsLoading(false); return; }
    if (notesResult.error) toast.error(`Collection notes unavailable: ${notesResult.error.message}. Apply collection migration.`);
    const customerRows = customersResult.data || [];
    const invoiceRows = invoicesResult.data || [];
    const customerById = new Map(customerRows.map((c) => [c.id, c]));
    setCustomers(customerRows.map((customer) => ({ ...customer, status: getCustomerStatus(customer, invoiceRows) })));
    setInvoices(invoiceRows.map((invoice) => { const days = Number(invoice.balance) > 0 ? daysPastDue(invoice.due_date) : 0; return { ...invoice, customerName: customerById.get(invoice.customer_id)?.name || 'Unknown Customer', statusView: getInvoiceStatus(invoice), daysOverdue: days, agingBucket: agingBucket(days) }; }));
    setPayments((paymentsResult.data || []) as PaymentRow[]);
    setNotes((notesResult.data || []) as CollectionNoteRow[]);
    setIsLoading(false);
  }, [businessId]);

  React.useEffect(() => { loadDebtors(); }, [loadDebtors]);
  React.useEffect(() => { if (!businessId) return undefined; const channel = supabase.channel(`debtors-${businessId}`).on('postgres_changes', { event: '*', schema: 'public', table: 'customers', filter: `business_id=eq.${businessId}` }, () => loadDebtors()).on('postgres_changes', { event: '*', schema: 'public', table: 'invoices', filter: `business_id=eq.${businessId}` }, () => loadDebtors()).on('postgres_changes', { event: '*', schema: 'public', table: 'payments', filter: `business_id=eq.${businessId}` }, () => loadDebtors()).subscribe(); return () => { supabase.removeChannel(channel); }; }, [businessId, loadDebtors]);

  const filteredCustomers = customers.filter((customer) => { const q = searchTerm.toLowerCase(); return (customer.name.toLowerCase().includes(q) || (customer.email || '').toLowerCase().includes(q) || (customer.phone || '').toLowerCase().includes(q)) && (statusFilter === 'all' || customer.status === statusFilter); });
  const filteredInvoices = invoices.filter((invoice) => { const q = searchTerm.toLowerCase(); return (invoice.invoice_number.toLowerCase().includes(q) || invoice.customerName.toLowerCase().includes(q)) && (statusFilter === 'all' || invoice.statusView === statusFilter); });
  const totalOutstanding = customers.reduce((sum, c) => sum + Number(c.current_balance), 0);
  const overdueReceivables = invoices.filter((i) => i.statusView === 'overdue').reduce((sum, i) => sum + Number(i.balance), 0);
  const totalCollected = payments.reduce((sum, p) => sum + Number(p.amount), 0);
  const totalInvoiced = invoices.reduce((sum, i) => sum + Number(i.total), 0);
  const collectionRate = totalInvoiced > 0 ? (totalCollected / totalInvoiced) * 100 : 0;
  const recoveredThisMonth = payments.filter((p) => new Date(p.created_at).getMonth() === new Date().getMonth()).reduce((sum, p) => sum + Number(p.amount), 0);
  const averageCollectionDays = invoices.length ? Math.round(invoices.reduce((sum, i) => sum + (Number(i.amount_paid) > 0 ? Math.max(0, daysPastDue(i.created_at) - daysPastDue(i.due_date)) : 0), 0) / invoices.length) : 0;
  const agingTotals = invoices.reduce<Record<AgingBucket, number>>((acc, invoice) => { if (Number(invoice.balance) > 0) acc[invoice.agingBucket] += Number(invoice.balance); return acc; }, { '0-30': 0, '31-60': 0, '61-90': 0, '91-180': 0, '180+': 0 });
  const topDebtors = [...customers].sort((a, b) => Number(b.current_balance) - Number(a.current_balance)).slice(0, 5);
  const highRiskDebtors = invoices.filter((i) => i.agingBucket === '91-180' || i.agingBucket === '180+').slice(0, 5);

  const createCustomer = async (event: React.FormEvent) => { event.preventDefault(); if (!businessId || !customerForm.name.trim()) return; setIsSaving(true); const { error } = await supabase.from('customers').insert({ business_id: businessId, name: customerForm.name.trim(), email: customerForm.email.trim() || null, phone: customerForm.phone.trim() || null, address: customerForm.address.trim() || null, credit_limit: Math.max(0, toNumber(customerForm.credit_limit)), is_active: true }); if (error) toast.error(`Could not create customer: ${error.message}`); else { toast.success('Customer created'); setShowAddCustomerModal(false); setCustomerForm(emptyCustomerForm); await loadDebtors(); } setIsSaving(false); };
  const openPaymentModal = (invoice: InvoiceView) => { setPaymentForm({ ...emptyPaymentForm, invoiceId: invoice.id, customerId: invoice.customer_id, amount: String(invoice.balance) }); setShowPaymentModal(true); };
  const openNoteModal = (invoice?: InvoiceView, customer?: CustomerView) => { setNoteForm({ ...emptyNoteForm, invoiceId: invoice?.id || '', customerId: invoice?.customer_id || customer?.id || '', nextFollowUpAt: '' }); setShowNoteModal(true); };

  const recordPayment = async (event: React.FormEvent) => { event.preventDefault(); if (!businessId) return; const amount = toNumber(paymentForm.amount); if (amount <= 0) return toast.error('Payment amount must be greater than zero.'); setIsSaving(true); const payment: PaymentInsert = { business_id: businessId, invoice_id: paymentForm.invoiceId, customer_id: paymentForm.customerId, amount, method: paymentForm.method, reference: paymentForm.reference.trim() || null, notes: paymentForm.notes.trim() || null, created_by: user?.id || null }; const { error } = await supabase.from('payments').insert(payment); if (error) toast.error(`Could not record payment: ${error.message}`); else { toast.success('Payment recorded'); setShowPaymentModal(false); setPaymentForm(emptyPaymentForm); await loadDebtors(); } setIsSaving(false); };
  const markFullyPaid = (invoice: InvoiceView) => { setPaymentForm({ ...emptyPaymentForm, invoiceId: invoice.id, customerId: invoice.customer_id, amount: String(invoice.balance), notes: 'Marked fully paid' }); setShowPaymentModal(true); };
  const reversePayment = async (payment: PaymentRow) => { if (!window.confirm('Reverse this payment? This will reopen the invoice balance.')) return; const { error } = await supabase.rpc('reverse_payment', { payment_id: payment.id, reversal_note: 'Payment reversed from Debtors screen' }); if (error) toast.error(`Could not reverse payment: ${error.message}`); else { toast.success('Payment reversed'); await loadDebtors(); } };
  const saveCollectionNote = async (event: React.FormEvent) => { event.preventDefault(); if (!businessId || !noteForm.customerId || !noteForm.note.trim()) return; const { error } = await supabase.from('collection_notes').insert({ business_id: businessId, customer_id: noteForm.customerId, invoice_id: noteForm.invoiceId || null, note: noteForm.note.trim(), priority: noteForm.priority, next_follow_up_at: noteForm.nextFollowUpAt || null, created_by: user?.id || null }); if (error) toast.error(`Could not save note: ${error.message}`); else { toast.success('Collection note saved'); setShowNoteModal(false); setNoteForm(emptyNoteForm); await loadDebtors(); } };

  const exportDebtors = () => { const headers = activeTab === 'customers' ? ['Customer', 'Email', 'Phone', 'Credit Limit', 'Balance', 'Total Purchases', 'Status'] : ['Invoice', 'Customer', 'Total', 'Paid', 'Balance', 'Due Date', 'Status', 'Aging']; const rows = activeTab === 'customers' ? filteredCustomers.map((c) => [c.name, c.email || '', c.phone || '', String(c.credit_limit), String(c.current_balance), String(c.total_purchases), c.status]) : filteredInvoices.map((i) => [i.invoice_number, i.customerName, String(i.total), String(i.amount_paid), String(i.balance), i.due_date, i.statusView, i.agingBucket]); download(`bizguard-${activeTab}-${new Date().toISOString().slice(0, 10)}.csv`, csv(headers, rows)); };
  const printInvoiceReceipt = (invoice: InvoiceView) => { const popup = window.open('', '_blank'); if (!popup) return toast.error('Popup blocked.'); popup.document.write(`<html><body style="font-family:Arial;padding:24px"><h2>BizGuard Statement</h2><p>${invoice.customerName}</p><p>${invoice.invoice_number}</p><p>Balance: ${formatCurrency(Number(invoice.balance))}</p><script>window.print()</script></body></html>`); popup.document.close(); };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><div><h1 className="text-2xl font-bold text-slate-800">Debtor Collection Engine</h1><p className="text-slate-500 mt-1">Collection management, aging analytics, payment history, notes, receipts and debtor recovery</p></div><div className="flex items-center gap-2"><button onClick={loadDebtors} disabled={isLoading} className="flex items-center gap-2 px-4 py-2 bg-white border border-slate-200 rounded-lg text-sm font-medium text-slate-700 hover:bg-slate-50 disabled:opacity-50"><RefreshCw className={cn('w-4 h-4', isLoading && 'animate-spin')} />Refresh</button><button onClick={exportDebtors} className="flex items-center gap-2 px-4 py-2 bg-white border border-slate-200 rounded-lg text-sm font-medium text-slate-700 hover:bg-slate-50"><Download className="w-4 h-4" />Export</button><button onClick={() => setShowAddCustomerModal(true)} className="flex items-center gap-2 px-4 py-2 bg-gradient-to-r from-emerald-500 to-cyan-500 text-white rounded-lg text-sm font-medium"><Plus className="w-4 h-4" />Add Customer</button></div></div>
      {error && <div className="bg-red-50 border border-red-200 text-red-700 rounded-xl p-4"><p className="font-medium">Debtors error</p><p className="text-sm mt-1">{error}</p></div>}

      <div className="grid grid-cols-1 sm:grid-cols-5 gap-4"><Stat label="Total Receivables" value={formatCurrency(totalOutstanding)} icon={DollarSign} /><Stat label="Overdue" value={formatCurrency(overdueReceivables)} icon={AlertCircle} /><Stat label="Collection Rate" value={`${collectionRate.toFixed(1)}%`} icon={TrendingUp} /><Stat label="Avg Collection Days" value={`${averageCollectionDays}d`} icon={RefreshCw} /><Stat label="Recovered This Month" value={formatCurrency(recoveredThisMonth)} icon={CreditCard} /></div>
      <div className="grid grid-cols-1 sm:grid-cols-5 gap-3">{(Object.keys(agingTotals) as AgingBucket[]).map((bucket) => <div key={bucket} className={cn('rounded-xl p-4 border', agingColors[bucket])}><p className="text-sm font-semibold">{bucket} Days</p><p className="text-xl font-black">{formatCurrency(agingTotals[bucket])}</p></div>)}</div>

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-2"><Panel title="Top Debtors">{topDebtors.map((c) => <div key={c.id} className="flex items-center justify-between rounded-lg bg-slate-50 p-3"><span className="font-medium text-slate-800">{c.name}</span><span className="font-bold text-red-600">{formatCurrency(Number(c.current_balance))}</span></div>)}</Panel><Panel title="Highest Risk Debts">{highRiskDebtors.map((i) => <div key={i.id} className="flex items-center justify-between rounded-lg bg-slate-50 p-3"><span><strong>{i.customerName}</strong><br /><small>{i.invoice_number} · {i.agingBucket}</small></span><span className="font-bold text-red-600">{formatCurrency(Number(i.balance))}</span></div>)}</Panel></div>

      <div className="bg-white rounded-xl border border-slate-200 shadow-sm"><div className="flex flex-wrap border-b border-slate-200">{(['customers','invoices','payments','aging','notes'] as const).map((tab) => <button key={tab} onClick={() => setActiveTab(tab)} className={cn('flex-1 px-4 py-3 text-sm font-medium capitalize transition-colors', activeTab === tab ? 'text-emerald-600 border-b-2 border-emerald-600' : 'text-slate-600 hover:text-slate-800')}>{tab}</button>)}</div><div className="p-4 border-b border-slate-200"><div className="flex flex-col sm:flex-row gap-4"><div className="flex-1 relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" /><input type="text" placeholder="Search..." value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} className="w-full pl-10 pr-4 py-2 border border-slate-200 rounded-lg text-sm" /></div><div className="flex items-center gap-2"><Filter className="w-4 h-4 text-slate-400" /><select value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)} className="px-3 py-2 border border-slate-200 rounded-lg text-sm"><option value="all">All Status</option><option value="active">Active</option><option value="overdue">Overdue</option><option value="paid">Paid</option><option value="partial">Partial</option></select></div></div></div><div className="overflow-x-auto">{isLoading ? <div className="py-12 text-center text-slate-500"><RefreshCw className="w-8 h-8 animate-spin mx-auto mb-3 text-emerald-500" />Loading debtors...</div> : activeTab === 'customers' ? <CustomersTable customers={filteredCustomers} openNoteModal={openNoteModal} /> : activeTab === 'invoices' ? <InvoicesTable invoices={filteredInvoices} openPaymentModal={openPaymentModal} markFullyPaid={markFullyPaid} printInvoiceReceipt={printInvoiceReceipt} openNoteModal={openNoteModal} /> : activeTab === 'payments' ? <PaymentsTable payments={payments} customers={customers} reversePayment={reversePayment} /> : activeTab === 'notes' ? <NotesTable notes={notes} customers={customers} /> : <AgingTable agingTotals={agingTotals} />}</div></div>

      {showAddCustomerModal && <Modal title="Add Customer" onClose={() => setShowAddCustomerModal(false)}><form onSubmit={createCustomer} className="space-y-4"><input required placeholder="Customer name" value={customerForm.name} onChange={(e) => setCustomerForm({ ...customerForm, name: e.target.value })} className="w-full px-3 py-2 border rounded-lg" /><input placeholder="Phone" value={customerForm.phone} onChange={(e) => setCustomerForm({ ...customerForm, phone: e.target.value })} className="w-full px-3 py-2 border rounded-lg" /><input placeholder="Email" value={customerForm.email} onChange={(e) => setCustomerForm({ ...customerForm, email: e.target.value })} className="w-full px-3 py-2 border rounded-lg" /><input type="number" placeholder="Credit limit" value={customerForm.credit_limit} onChange={(e) => setCustomerForm({ ...customerForm, credit_limit: e.target.value })} className="w-full px-3 py-2 border rounded-lg" /><textarea placeholder="Address" value={customerForm.address} onChange={(e) => setCustomerForm({ ...customerForm, address: e.target.value })} className="w-full px-3 py-2 border rounded-lg" /><button disabled={isSaving} className="w-full rounded-lg bg-emerald-600 py-2 font-bold text-white">{isSaving ? 'Saving...' : 'Save Customer'}</button></form></Modal>}
      {showPaymentModal && <Modal title="Record Payment / Part Payment" onClose={() => setShowPaymentModal(false)}><form onSubmit={recordPayment} className="space-y-4"><input type="number" min="0.01" step="0.01" value={paymentForm.amount} onChange={(e) => setPaymentForm({ ...paymentForm, amount: e.target.value })} className="w-full px-3 py-2 border rounded-lg" /><select value={paymentForm.method} onChange={(e) => setPaymentForm({ ...paymentForm, method: e.target.value as PaymentFormState['method'] })} className="w-full px-3 py-2 border rounded-lg"><option value="cash">Cash</option><option value="card">Card</option><option value="mobile">Wallet/Mobile</option><option value="bank_transfer">Bank Transfer</option></select><input placeholder="Reference" value={paymentForm.reference} onChange={(e) => setPaymentForm({ ...paymentForm, reference: e.target.value })} className="w-full px-3 py-2 border rounded-lg" /><textarea placeholder="Payment notes" value={paymentForm.notes} onChange={(e) => setPaymentForm({ ...paymentForm, notes: e.target.value })} className="w-full px-3 py-2 border rounded-lg" /><button disabled={isSaving} className="w-full rounded-lg bg-emerald-600 py-2 font-bold text-white">{isSaving ? 'Saving...' : 'Record Payment'}</button></form></Modal>}
      {showNoteModal && <Modal title="Collection Note" onClose={() => setShowNoteModal(false)}><form onSubmit={saveCollectionNote} className="space-y-4"><textarea required placeholder="Collection note, promise to pay, call outcome..." value={noteForm.note} onChange={(e) => setNoteForm({ ...noteForm, note: e.target.value })} className="w-full px-3 py-2 border rounded-lg" /><select value={noteForm.priority} onChange={(e) => setNoteForm({ ...noteForm, priority: e.target.value as NoteFormState['priority'] })} className="w-full px-3 py-2 border rounded-lg"><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select><input type="datetime-local" value={noteForm.nextFollowUpAt} onChange={(e) => setNoteForm({ ...noteForm, nextFollowUpAt: e.target.value })} className="w-full px-3 py-2 border rounded-lg" /><button className="w-full rounded-lg bg-slate-900 py-2 font-bold text-white">Save Note</button></form></Modal>}
    </div>
  );
};

const Stat: React.FC<{ label: string; value: string; icon: typeof DollarSign }> = ({ label, value, icon: Icon }) => <div className="bg-white rounded-xl p-6 border border-slate-200 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-sm text-slate-500">{label}</p><p className="text-2xl font-bold text-slate-800 mt-1">{value}</p></div><div className="w-12 h-12 rounded-xl bg-gradient-to-br from-emerald-500 to-cyan-600 flex items-center justify-center"><Icon className="w-6 h-6 text-white" /></div></div></div>;
const Panel: React.FC<{ title: string; children: React.ReactNode }> = ({ title, children }) => <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 font-bold text-slate-800">{title}</h2><div className="space-y-2">{children}</div></div>;
const Modal: React.FC<{ title: string; onClose: () => void; children: React.ReactNode }> = ({ title, onClose, children }) => <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4"><div className="bg-white rounded-2xl w-full max-w-lg"><div className="p-6 border-b border-slate-200 flex items-center justify-between"><h2 className="text-xl font-bold text-slate-800">{title}</h2><button type="button" onClick={onClose} className="p-2 hover:bg-slate-100 rounded-lg"><X className="w-5 h-5" /></button></div><div className="p-6">{children}</div></div></div>;

const CustomersTable: React.FC<{ customers: CustomerView[]; openNoteModal: (invoice?: InvoiceView, customer?: CustomerView) => void }> = ({ customers, openNoteModal }) => <table className="w-full"><thead className="bg-slate-50"><tr><th className="px-6 py-3 text-left text-xs font-semibold uppercase text-slate-600">Customer</th><th className="px-6 py-3 text-left text-xs font-semibold uppercase text-slate-600">Contact</th><th className="px-6 py-3 text-left text-xs font-semibold uppercase text-slate-600">Balance</th><th className="px-6 py-3 text-left text-xs font-semibold uppercase text-slate-600">Status</th><th className="px-6 py-3 text-right text-xs font-semibold uppercase text-slate-600">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{customers.map((c) => <tr key={c.id}><td className="px-6 py-4"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-full bg-gradient-to-br from-emerald-400 to-cyan-500 flex items-center justify-center"><span className="text-white font-semibold text-sm">{getInitials(c.name)}</span></div><span className="font-medium text-slate-800">{c.name}</span></div></td><td className="px-6 py-4 text-sm text-slate-600"><Phone className="inline w-3 h-3 mr-1" />{c.phone || 'No phone'}<br /><Mail className="inline w-3 h-3 mr-1" />{c.email || 'No email'}</td><td className="px-6 py-4 font-bold text-red-600">{formatCurrency(Number(c.current_balance))}</td><td className="px-6 py-4"><span className={cn('px-2.5 py-1 text-xs font-medium rounded-full', statusColors[c.status])}>{c.status}</span></td><td className="px-6 py-4 text-right"><button onClick={() => openNoteModal(undefined, c)} className="text-xs font-bold text-emerald-700"><StickyNote className="inline h-3 w-3" /> Note</button></td></tr>)}</tbody></table>;
const InvoicesTable: React.FC<{ invoices: InvoiceView[]; openPaymentModal: (invoice: InvoiceView) => void; markFullyPaid: (invoice: InvoiceView) => void; printInvoiceReceipt: (invoice: InvoiceView) => void; openNoteModal: (invoice?: InvoiceView) => void }> = ({ invoices, openPaymentModal, markFullyPaid, printInvoiceReceipt, openNoteModal }) => <table className="w-full"><thead className="bg-slate-50"><tr><th className="px-6 py-3 text-left text-xs font-semibold uppercase text-slate-600">Invoice</th><th className="px-6 py-3 text-left text-xs font-semibold uppercase text-slate-600">Customer</th><th className="px-6 py-3 text-left text-xs font-semibold uppercase text-slate-600">Balance</th><th className="px-6 py-3 text-left text-xs font-semibold uppercase text-slate-600">Aging</th><th className="px-6 py-3 text-right text-xs font-semibold uppercase text-slate-600">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{invoices.map((i) => <tr key={i.id}><td className="px-6 py-4 font-medium">{i.invoice_number}<br /><small>{formatDate(i.due_date)}</small></td><td className="px-6 py-4">{i.customerName}</td><td className="px-6 py-4 font-bold text-red-600">{formatCurrency(Number(i.balance))}</td><td className="px-6 py-4"><span className={cn('px-2.5 py-1 text-xs font-bold rounded-full', agingColors[i.agingBucket])}>{i.agingBucket}</span></td><td className="px-6 py-4 text-right space-x-2">{Number(i.balance) > 0 && <><button onClick={() => openPaymentModal(i)} className="text-xs font-bold text-emerald-700"><CreditCard className="inline h-3 w-3" /> Pay</button><button onClick={() => markFullyPaid(i)} className="text-xs font-bold text-blue-700">Mark Paid</button></>}<button onClick={() => openNoteModal(i)} className="text-xs font-bold text-slate-700">Note</button><button onClick={() => printInvoiceReceipt(i)} className="text-xs font-bold text-purple-700"><Printer className="inline h-3 w-3" /> Print</button></td></tr>)}</tbody></table>;
const PaymentsTable: React.FC<{ payments: PaymentRow[]; customers: CustomerView[]; reversePayment: (payment: PaymentRow) => void }> = ({ payments, customers, reversePayment }) => { const customerById = new Map(customers.map((c) => [c.id, c.name])); return <table className="w-full"><thead className="bg-slate-50"><tr><th className="px-6 py-3 text-left text-xs font-semibold uppercase text-slate-600">Date</th><th className="px-6 py-3 text-left text-xs font-semibold uppercase text-slate-600">Customer</th><th className="px-6 py-3 text-left text-xs font-semibold uppercase text-slate-600">Amount</th><th className="px-6 py-3 text-left text-xs font-semibold uppercase text-slate-600">Method</th><th className="px-6 py-3 text-right text-xs font-semibold uppercase text-slate-600">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{payments.map((p) => <tr key={p.id}><td className="px-6 py-4">{formatDate(p.created_at)}</td><td className="px-6 py-4">{customerById.get(p.customer_id) || p.customer_id}</td><td className="px-6 py-4 font-bold text-emerald-700">{formatCurrency(Number(p.amount))}</td><td className="px-6 py-4 capitalize">{p.method}</td><td className="px-6 py-4 text-right"><button onClick={() => reversePayment(p)} className="text-xs font-bold text-red-700"><RotateCcw className="inline h-3 w-3" /> Reverse</button></td></tr>)}</tbody></table>; };
const NotesTable: React.FC<{ notes: CollectionNoteRow[]; customers: CustomerView[] }> = ({ notes, customers }) => { const customerById = new Map(customers.map((c) => [c.id, c.name])); return <div className="space-y-3 p-4">{notes.length === 0 ? <p className="text-sm text-slate-500">No collection notes yet.</p> : notes.map((n) => <div key={n.id} className="rounded-lg border border-slate-200 p-4"><div className="flex justify-between"><p className="font-bold text-slate-800">{customerById.get(n.customer_id) || 'Customer'}</p><span className="text-xs text-slate-400">{formatDate(n.created_at)}</span></div><p className="mt-2 text-sm text-slate-600">{n.note}</p><p className="mt-2 text-xs font-bold uppercase text-emerald-700">{n.priority}</p></div>)}</div>; };
const AgingTable: React.FC<{ agingTotals: Record<AgingBucket, number> }> = ({ agingTotals }) => <div className="grid grid-cols-1 gap-4 p-6 md:grid-cols-5">{(Object.keys(agingTotals) as AgingBucket[]).map((b) => <div key={b} className={cn('rounded-xl border p-5', agingColors[b])}><p className="text-sm font-bold">{b} Days</p><p className="mt-2 text-xl font-black">{formatCurrency(agingTotals[b])}</p><p className="mt-2 text-xs">Priority: {b === '0-30' ? 'Monitor' : b === '31-60' ? 'Follow up' : b === '61-90' ? 'Escalate' : 'Urgent recovery'}</p></div>)}</div>;

export default Debtors;
